import { daysAgoIso } from "@/lib/utils";
const img = (id, w = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;
export async function seedIfEmpty(sql) {
  const existing = await sql`select count(*)::int as count from property_types`;
  if ((existing[0]?.count ?? 0) > 0) return;
  const types = [
    ["apartment", "Apartment", "residential", 1],
    ["house", "House", "residential", 2],
    ["duplex", "Duplex", "residential", 3],
    ["villa", "Villa", "residential", 4],
    ["penthouse", "Penthouse", "residential", 5],
    ["bungalow", "Bungalow", "residential", 6],
    ["land", "Land", "land", 7],
    ["office", "Office", "commercial", 8],
    ["shop", "Shop", "commercial", 9],
    ["warehouse", "Warehouse", "commercial", 10],
    ["commercial", "Commercial property", "commercial", 11],
  ];
  for (const [slug, name, category, sort] of types) {
    await sql`insert into property_types (slug, name, category, sort_order) values (${slug}, ${name}, ${category}, ${sort})`;
  }
  const amenities = [
    ["swimming-pool", "Swimming pool", "Waves", 1],
    ["parking", "Parking", "Car", 2],
    ["generator", "Generator", "Zap", 3],
    ["security", "Security", "Shield", 4],
    ["air-conditioning", "Air conditioning", "Wind", 5],
    ["furnished", "Furnished", "Sofa", 6],
    ["garden", "Garden", "Flower2", 7],
    ["balcony", "Balcony", "Maximize2", 8],
    ["gym", "Gym", "Dumbbell", 9],
    ["cctv", "CCTV", "Cctv", 10],
    ["electricity", "24/7 electricity", "Plug", 11],
    ["water", "Water supply", "Droplets", 12],
    ["elevator", "Elevator", "ArrowUpDown", 13],
    ["smart-home", "Smart home", "Cpu", 14],
    ["bq", "Boys' quarters", "Home", 15],
  ];
  for (const [slug, name, icon, sort] of amenities) {
    await sql`insert into amenities (slug, name, icon, sort_order) values (${slug}, ${name}, ${icon}, ${sort})`;
  }
  const agencies = [
    {
      id: "agc_northbridge",
      slug: "northbridge-and-co",
      name: "Northbridge & Co.",
      description:
        "A discreet Abuja practice representing diplomatic residences, Maitama compounds, and considered new-build villas. Established 2009.",
      email: "desk@northbridge.ng",
      phone: "+234 809 441 2200",
      website: "https://northbridge.example",
      address: "12 Aguiyi Ironsi Street",
      city: "Abuja",
      state: "FCT",
      lat: 9.0765,
      lng: 7.4913,
      cover: img("photo-1486406146926-c627a92ad1ab"),
    },
    {
      id: "agc_atelier",
      slug: "atelier-homes",
      name: "Atelier Homes",
      description:
        "Lagos-based specialists in Ikoyi, Victoria Island and Banana Island. Architecture-led brokerage for private clients and family offices.",
      email: "hello@atelierhomes.ng",
      phone: "+234 802 118 4401",
      website: "https://atelierhomes.example",
      address: "14 Gerrard Road, Ikoyi",
      city: "Lagos",
      state: "Lagos",
      lat: 6.4541,
      lng: 3.4316,
      cover: img("photo-1486406146926-c627a92ad1ab", 1800),
    },
    {
      id: "agc_capitalcrest",
      slug: "capital-crest",
      name: "Capital Crest",
      description:
        "Full-service agency covering Port Harcourt GRA and selected Abuja stock. Strong in corporate lets and family compounds.",
      email: "enquiries@capitalcrest.ng",
      phone: "+234 803 220 9188",
      website: "https://capitalcrest.example",
      address: "Tombia Street, GRA Phase 2",
      city: "Port Harcourt",
      state: "Rivers",
      lat: 4.8242,
      lng: 7.0336,
      cover: img("photo-1497366754035-f200968a6e72"),
    },
  ];
  for (const a of agencies) {
    await sql`
      insert into agencies (
        id, slug, name, description, email, phone, website, address, city, state, country, lat, lng, is_verified, cover_url
      ) values (
        ${a.id}, ${a.slug}, ${a.name}, ${a.description}, ${a.email}, ${a.phone}, ${a.website},
        ${a.address}, ${a.city}, ${a.state}, 'Nigeria', ${a.lat}, ${a.lng}, true, ${a.cover}
      )`;
  }
  const agents = [
    {
      id: "agt_amara",
      agency: "agc_northbridge",
      slug: "amara-okonkwo",
      name: "Amara Okonkwo",
      title: "Principal, Residential",
      bio: "Amara leads Northbridge's private-client desk. Fifteen years placing families in Maitama, Asokoro and Wuse 2, with a particular eye for quiet compounds and embassy-grade security.",
      image: img("photo-1573496359142-b8d87734a5a2", 800),
      email: "amara@northbridge.ng",
      phone: "+234 809 441 2201",
      years: 15,
      spec: "Villas, Diplomatic residences, Abuja",
    },
    {
      id: "agt_chinedu",
      agency: "agc_northbridge",
      slug: "chinedu-eze",
      name: "Chinedu Eze",
      title: "Associate Director",
      bio: "Chinedu handles new-build duplexes and land assemblies across the FCT. Formerly with a quantity-surveying practice, he is exacting on specifications and title.",
      image: img("photo-1560250097-0b93528c311a", 800),
      email: "chinedu@northbridge.ng",
      phone: "+234 809 441 2204",
      years: 11,
      spec: "Duplexes, Land, New builds",
    },
    {
      id: "agt_tunde",
      agency: "agc_atelier",
      slug: "tunde-balogun",
      name: "Tunde Balogun",
      title: "Managing Partner",
      bio: "Tunde founded Atelier after a decade in London residential sales. He represents waterfront and island stock, and advises on off-plan at the upper end of the Lagos market.",
      image: img("photo-1519085360753-af0119f7cbe7", 800),
      email: "tunde@atelierhomes.ng",
      phone: "+234 802 118 4401",
      years: 18,
      spec: "Penthouses, Waterfront, Ikoyi",
    },
    {
      id: "agt_ifeoma",
      agency: "agc_atelier",
      slug: "ifeoma-nwosu",
      name: "Ifeoma Nwosu",
      title: "Senior Negotiator",
      bio: "Ifeoma specialises in Lekki and Victoria Island apartments for relocating professionals. Known for calm viewings and unusually thorough inventories.",
      image: img("photo-1580489944761-15a19d654956", 800),
      email: "ifeoma@atelierhomes.ng",
      phone: "+234 802 118 4408",
      years: 9,
      spec: "Apartments, Short lets, Lekki",
    },
    {
      id: "agt_fatima",
      agency: "agc_capitalcrest",
      slug: "fatima-bello",
      name: "Fatima Bello",
      title: "Head of Lettings",
      bio: "Fatima manages Capital Crest's corporate letting book — oil-and-gas housing, GRA compounds, and selected Abuja stock for rotating staff.",
      image: img("photo-1594744803329-e58b31de8bf5", 800),
      email: "fatima@capitalcrest.ng",
      phone: "+234 803 220 9188",
      years: 12,
      spec: "Lettings, Corporate, GRA",
    },
    {
      id: "agt_yusuf",
      agency: "agc_capitalcrest",
      slug: "yusuf-ibrahim",
      name: "Yusuf Ibrahim",
      title: "Commercial Broker",
      bio: "Yusuf covers offices, warehouses and mixed-use plots from Port Harcourt to Kano. He prefers long-lease covenants and clear planning status.",
      image: img("photo-1472099645785-5658abf4ff4e", 800),
      email: "yusuf@capitalcrest.ng",
      phone: "+234 803 220 9190",
      years: 14,
      spec: "Offices, Warehouses, Commercial",
    },
  ];
  for (const a of agents) {
    await sql`
      insert into agents (
        id, agency_id, slug, name, title, bio, image_url, email, phone, years_experience, is_verified, specializations
      ) values (
        ${a.id}, ${a.agency}, ${a.slug}, ${a.name}, ${a.title}, ${a.bio}, ${a.image},
        ${a.email}, ${a.phone}, ${a.years}, true, ${a.spec}
      )`;
  }
  const typeRows = await sql`select id, slug from property_types`;
  const typeId = (slug) => typeRows.find((t) => t.slug === slug).id;
  const amenityRows = await sql`select id, slug from amenities`;
  const amenityId = (slug) => amenityRows.find((a) => a.slug === slug).id;
  const properties = [
    {
      id: "prop_wuse_duplex",
      slug: "luxury-4-bedroom-duplex-wuse-2",
      title: "Luxury 4 Bedroom Duplex",
      description:
        "A composed family duplex on a quiet Wuse 2 street, finished in pale stone and warm timber. Four bedrooms sit above a generous living floor with a garden terrace and a separate BQ. The house has been rewired, the roof recently replaced, and the compound is fully fenced with 24-hour security. Suitable as a principal residence or a discreet diplomatic let.",
      listingType: "SALE",
      type: "duplex",
      status: "AVAILABLE",
      price: 85_000_000,
      bedrooms: 4,
      bathrooms: 5,
      toilets: 6,
      parking: 4,
      size: 450,
      land: 650,
      year: 2019,
      address: "14 Ibrahim Taiwo Street",
      area: "Wuse 2",
      city: "Abuja",
      state: "FCT",
      lat: 9.076,
      lng: 7.475,
      agent: "agt_amara",
      agency: "agc_northbridge",
      featured: true,
      verified: true,
      daysAgo: 6,
      views: 1840,
      images: [
        img("photo-1600596542815-ffad4c1539a9"),
        img("photo-1600607687939-ce8a6c25118c"),
        img("photo-1600566753190-17f0baa2a6c3"),
        img("photo-1600210492486-724fe5c67fb0"),
      ],
      amenities: [
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "garden",
        "cctv",
        "electricity",
        "water",
        "bq",
      ],
    },
    {
      id: "prop_maitama_villa",
      slug: "maitama-courtyard-villa",
      title: "Maitama Courtyard Villa",
      description:
        "Set behind a high wall on a residential Maitama crescent, this villa is organised around a planted courtyard. Six bedrooms, a formal dining room, a library, and a pool pavilion. The specification is embassy-grade: treated water, dual generators, and a staff wing. Offered with vacant possession.",
      listingType: "SALE",
      type: "villa",
      status: "AVAILABLE",
      price: 620_000_000,
      bedrooms: 6,
      bathrooms: 7,
      toilets: 8,
      parking: 6,
      size: 980,
      land: 1800,
      year: 2016,
      address: "9 Mississippi Street",
      area: "Maitama",
      city: "Abuja",
      state: "FCT",
      lat: 9.088,
      lng: 7.492,
      agent: "agt_amara",
      agency: "agc_northbridge",
      featured: true,
      verified: true,
      daysAgo: 18,
      views: 960,
      images: [
        img("photo-1613490493576-7fde63acd811"),
        img("photo-1512917774080-9991f1c4c750"),
        img("photo-1600573472592-401b489a3cdc"),
        img("photo-1600047509807-ba8f99d2cdbc"),
      ],
      amenities: [
        "swimming-pool",
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "garden",
        "gym",
        "cctv",
        "electricity",
        "water",
        "bq",
        "smart-home",
      ],
    },
    {
      id: "prop_ikoyi_penthouse",
      slug: "ikoyi-waterfront-penthouse",
      title: "Ikoyi Waterfront Penthouse",
      description:
        "A full-floor penthouse facing the lagoon, with 3.6m ceilings and a wraparound terrace. Three bedroom suites, a study, and a kitchen by Boffi. The building is 12 storeys, with two lifts, a gym, and basement parking. Service charge is current. A rare lateral apartment in a quiet pocket of old Ikoyi.",
      listingType: "SALE",
      type: "penthouse",
      status: "AVAILABLE",
      price: 890_000_000,
      bedrooms: 3,
      bathrooms: 4,
      toilets: 4,
      parking: 3,
      size: 420,
      year: 2021,
      address: "Banana Island Approach, Ikoyi",
      area: "Ikoyi",
      city: "Lagos",
      state: "Lagos",
      lat: 6.4501,
      lng: 3.435,
      agent: "agt_tunde",
      agency: "agc_atelier",
      featured: true,
      verified: true,
      daysAgo: 4,
      views: 2310,
      images: [
        img("photo-1600607687644-c7171b42498b"),
        img("photo-1600607687920-4e2a09cf159d"),
        img("photo-1600210492486-724fe5c67fb0"),
        img("photo-1600566753190-17f0baa2a6c3"),
      ],
      amenities: [
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "furnished",
        "balcony",
        "gym",
        "cctv",
        "electricity",
        "water",
        "elevator",
        "smart-home",
      ],
    },
    {
      id: "prop_banana_villa",
      slug: "banana-island-family-compound",
      title: "Banana Island Family Compound",
      description:
        "A walled compound on Banana Island with a principal house, guest pavilion, and 18m pool. Seven bedrooms in total. Built for a family that entertains: a double-height hall, a wine room, and a covered outdoor kitchen. Title is C of O. Viewing strictly by appointment.",
      listingType: "SALE",
      type: "villa",
      status: "UNDER_OFFER",
      price: 1_850_000_000,
      bedrooms: 7,
      bathrooms: 8,
      toilets: 9,
      parking: 8,
      size: 1400,
      land: 2400,
      year: 2018,
      address: "Plot 22, Banana Island",
      area: "Banana Island",
      city: "Lagos",
      state: "Lagos",
      lat: 6.4667,
      lng: 3.45,
      agent: "agt_tunde",
      agency: "agc_atelier",
      featured: true,
      verified: true,
      daysAgo: 40,
      views: 1544,
      images: [
        img("photo-1564013799919-ab600027ffc6"),
        img("photo-1512917774080-9991f1c4c750"),
        img("photo-1613490493576-7fde63acd811"),
        img("photo-1600585154340-be6161a56a0c"),
      ],
      amenities: [
        "swimming-pool",
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "garden",
        "gym",
        "cctv",
        "electricity",
        "water",
        "bq",
        "smart-home",
      ],
    },
    {
      id: "prop_lekki_apt",
      slug: "lekki-phase-1-serviced-apartment",
      title: "Serviced 3 Bedroom Apartment, Lekki",
      description:
        "A bright, fully furnished apartment in a managed block off Admiralty Way. Three bedrooms, two bathrooms, a balcony over the courtyard, and reliable estate power. Ideal for a professional couple or a short corporate posting. Estate service charge included in the quoted rent.",
      listingType: "RENT",
      type: "apartment",
      status: "AVAILABLE",
      price: 12_000_000,
      bedrooms: 3,
      bathrooms: 3,
      toilets: 3,
      parking: 2,
      size: 168,
      year: 2020,
      address: "Admiralty Way",
      area: "Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      lat: 6.4474,
      lng: 3.4723,
      agent: "agt_ifeoma",
      agency: "agc_atelier",
      verified: true,
      daysAgo: 9,
      views: 720,
      images: [
        img("photo-1502672260266-1c1ef2d93688"),
        img("photo-1522708323590-d24dbb6b0267"),
        img("photo-1560448204-e02f11c3d0e2"),
        img("photo-1484154218962-a197022b5858"),
      ],
      amenities: [
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "furnished",
        "balcony",
        "cctv",
        "electricity",
        "water",
      ],
    },
    {
      id: "prop_vi_shortlet",
      slug: "victoria-island-short-let-suite",
      title: "Victoria Island Short-Let Suite",
      description:
        "A hotel-grade one-bedroom suite on Kofo Abayomi, let by the night. Housekeeping three times weekly, airport transfer on request, and a concierge desk in the lobby. Suitable for visiting executives who prefer an apartment to a hotel.",
      listingType: "SHORT_LET",
      type: "apartment",
      status: "AVAILABLE",
      price: 85_000,
      bedrooms: 1,
      bathrooms: 1,
      toilets: 1,
      parking: 1,
      size: 72,
      year: 2022,
      address: "Kofo Abayomi Street",
      area: "Victoria Island",
      city: "Lagos",
      state: "Lagos",
      lat: 6.4281,
      lng: 3.4219,
      agent: "agt_ifeoma",
      agency: "agc_atelier",
      verified: true,
      daysAgo: 2,
      views: 410,
      images: [
        img("photo-1522708323590-d24dbb6b0267"),
        img("photo-1600210492486-724fe5c67fb0"),
        img("photo-1600566753190-17f0baa2a6c3"),
      ],
      amenities: [
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "furnished",
        "gym",
        "cctv",
        "electricity",
        "water",
        "elevator",
      ],
    },
    {
      id: "prop_asokoro_bungalow",
      slug: "asokoro-single-storey-bungalow",
      title: "Asokoro Single-Storey Bungalow",
      description:
        "A low, spreading bungalow on a corner plot in Asokoro. Three bedrooms, a deep veranda, and a mature garden. Recently painted, with a new borehole. Quiet, shaded, and a short drive from the villa district. Offered for sale with vacant possession.",
      listingType: "SALE",
      type: "bungalow",
      status: "AVAILABLE",
      price: 145_000_000,
      bedrooms: 3,
      bathrooms: 3,
      toilets: 4,
      parking: 3,
      size: 280,
      land: 900,
      year: 2008,
      address: "Udi Street",
      area: "Asokoro",
      city: "Abuja",
      state: "FCT",
      lat: 9.041,
      lng: 7.526,
      agent: "agt_chinedu",
      agency: "agc_northbridge",
      verified: true,
      daysAgo: 21,
      views: 388,
      images: [
        img("photo-1570129477492-45c003edd2be"),
        img("photo-1600585154340-be6161a56a0c"),
        img("photo-1600573472592-401b489a3cdc"),
      ],
      amenities: ["parking", "generator", "security", "garden", "water", "electricity"],
    },
    {
      id: "prop_jahi_house",
      slug: "jahi-contemporary-family-house",
      title: "Jahi Contemporary Family House",
      description:
        "A five-bedroom house on two floors, completed last year to a clean, contemporary specification. Open kitchen, a first-floor family sitting room, and a roof terrace. The street is gated. A practical family house at a considered price for the district.",
      listingType: "SALE",
      type: "house",
      status: "AVAILABLE",
      price: 195_000_000,
      bedrooms: 5,
      bathrooms: 5,
      toilets: 6,
      parking: 4,
      size: 520,
      land: 600,
      year: 2025,
      address: "Jahi District, Cadastral Zone",
      area: "Jahi",
      city: "Abuja",
      state: "FCT",
      lat: 9.077,
      lng: 7.435,
      agent: "agt_chinedu",
      agency: "agc_northbridge",
      verified: true,
      daysAgo: 3,
      views: 512,
      images: [
        img("photo-1600585154340-be6161a56a0c"),
        img("photo-1600607687939-ce8a6c25118c"),
        img("photo-1600047509807-ba8f99d2cdbc"),
        img("photo-1600566753190-17f0baa2a6c3"),
      ],
      amenities: [
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "garden",
        "balcony",
        "cctv",
        "electricity",
        "water",
      ],
    },
    {
      id: "prop_ph_gra_rent",
      slug: "port-harcourt-gra-compound",
      title: "Port Harcourt GRA Compound",
      description:
        "A four-bedroom compound in GRA Phase 2, let as a whole. Generator, borehole, and a small pool. Popular with rotating oil-and-gas staff. The landlord prefers a two-year term with a corporate covenant. Available from the first of next month.",
      listingType: "RENT",
      type: "house",
      status: "AVAILABLE",
      price: 18_000_000,
      bedrooms: 4,
      bathrooms: 4,
      toilets: 5,
      parking: 4,
      size: 360,
      land: 800,
      year: 2014,
      address: "Tombia Extension, GRA Phase 2",
      area: "GRA Phase 2",
      city: "Port Harcourt",
      state: "Rivers",
      lat: 4.824,
      lng: 7.038,
      agent: "agt_fatima",
      agency: "agc_capitalcrest",
      verified: true,
      daysAgo: 11,
      views: 266,
      availableFrom: new Date(Date.now() + 20 * 86_400_000).toISOString().slice(0, 10),
      images: [
        img("photo-1580587771525-78b9dba3b26c"),
        img("photo-1600573472592-401b489a3cdc"),
        img("photo-1600596542815-ffad4c1539a9"),
      ],
      amenities: [
        "swimming-pool",
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "garden",
        "cctv",
        "electricity",
        "water",
        "bq",
      ],
    },
    {
      id: "prop_vi_office",
      slug: "victoria-island-fitted-office",
      title: "Fitted Office Floor, Victoria Island",
      description:
        "An entire 420 sqm floor in a mid-rise on Adeola Odeku, let as a single suite. Raised floors, a meeting room, a tea point, and 10 allocated parking bays. The building has a generator, treated water, and 24-hour security. Lease from three years.",
      listingType: "LEASE",
      type: "office",
      status: "AVAILABLE",
      price: 45_000_000,
      parking: 10,
      size: 420,
      year: 2017,
      address: "Adeola Odeku Street",
      area: "Victoria Island",
      city: "Lagos",
      state: "Lagos",
      lat: 6.428,
      lng: 3.422,
      agent: "agt_yusuf",
      agency: "agc_capitalcrest",
      verified: true,
      daysAgo: 28,
      views: 190,
      images: [
        img("photo-1497366754035-f200968a6e72"),
        img("photo-1497366216548-37526070297c"),
        img("photo-1486406146926-c627a92ad1ab"),
      ],
      amenities: [
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "cctv",
        "electricity",
        "water",
        "elevator",
      ],
    },
    {
      id: "prop_apapa_warehouse",
      slug: "apapa-warehouse-with-yard",
      title: "Apapa Warehouse with Yard",
      description:
        "A 1,800 sqm warehouse on a fenced plot close to the port access road. 8m eaves, two loading docks, a small office, and a 24-hour security post. Power from the estate plus a 250 kVA generator. Offered on a five-year lease.",
      listingType: "LEASE",
      type: "warehouse",
      status: "AVAILABLE",
      price: 36_000_000,
      parking: 12,
      size: 1800,
      land: 3200,
      year: 2012,
      address: "Creek Road corridor",
      area: "Apapa",
      city: "Lagos",
      state: "Lagos",
      lat: 6.448,
      lng: 3.359,
      agent: "agt_yusuf",
      agency: "agc_capitalcrest",
      daysAgo: 55,
      views: 88,
      images: [img("photo-1586528116311-ad8dd3fc8380"), img("photo-1553413077-190dd305871c")],
      amenities: ["parking", "generator", "security", "cctv", "electricity"],
    },
    {
      id: "prop_lekki_land",
      slug: "lekki-free-trade-zone-land",
      title: "Lekki Free Trade Zone Plot",
      description:
        "A 2,000 sqm serviced plot within a gated scheme near the Free Trade Zone. Roads, drainage and power are in. Dry land, rectangular, with C of O in process — governor's consent available on request. Suitable for a family house or a pair of duplexes.",
      listingType: "SALE",
      type: "land",
      status: "AVAILABLE",
      price: 95_000_000,
      land: 2000,
      address: "Lekki Free Trade Zone scheme",
      area: "Lekki",
      city: "Lagos",
      state: "Lagos",
      lat: 6.46,
      lng: 3.88,
      agent: "agt_chinedu",
      agency: "agc_northbridge",
      verified: true,
      daysAgo: 16,
      views: 301,
      images: [img("photo-1500382017468-9049fed747ef"), img("photo-1464146072230-91cabc968266")],
      amenities: ["security", "electricity", "water"],
    },
    {
      id: "prop_enugu_duplex",
      slug: "independence-layout-duplex-enugu",
      title: "Independence Layout Duplex",
      description:
        "A well-kept four-bedroom duplex in Independence Layout. Terrazzo floors, a large kitchen, and a walled garden. The neighbourhood is established and quiet. Offered for sale to a private buyer; no chain.",
      listingType: "SALE",
      type: "duplex",
      status: "AVAILABLE",
      price: 78_000_000,
      bedrooms: 4,
      bathrooms: 4,
      toilets: 5,
      parking: 3,
      size: 380,
      land: 540,
      year: 2011,
      address: "Thinkers Corner approach",
      area: "Independence Layout",
      city: "Enugu",
      state: "Enugu",
      lat: 6.452,
      lng: 7.531,
      agent: "agt_fatima",
      agency: "agc_capitalcrest",
      daysAgo: 33,
      views: 142,
      images: [
        img("photo-1605276374104-dee2a0ed3cd6"),
        img("photo-1600585154340-be6161a56a0c"),
        img("photo-1600566753190-17f0baa2a6c3"),
      ],
      amenities: ["parking", "generator", "security", "garden", "water"],
    },
    {
      id: "prop_magodo_sold",
      slug: "magodo-phase-2-terrace",
      title: "Magodo Phase 2 Terrace",
      description:
        "A four-bedroom terrace in a gated Magodo close. Recently sold to a private buyer. Retained on the platform as a comparable for the street.",
      listingType: "SALE",
      type: "house",
      status: "SOLD",
      price: 165_000_000,
      bedrooms: 4,
      bathrooms: 4,
      toilets: 5,
      parking: 2,
      size: 310,
      land: 280,
      year: 2015,
      address: "Command Road, Magodo GRA",
      area: "Magodo",
      city: "Lagos",
      state: "Lagos",
      lat: 6.618,
      lng: 3.379,
      agent: "agt_ifeoma",
      agency: "agc_atelier",
      verified: true,
      daysAgo: 80,
      views: 990,
      images: [img("photo-1570129477492-45c003edd2be"), img("photo-1560448204-e02f11c3d0e2")],
      amenities: ["parking", "generator", "security", "air-conditioning"],
    },
    {
      id: "prop_wuse_rented",
      slug: "wuse-2-two-bedroom-flat",
      title: "Wuse 2 Two-Bedroom Flat",
      description:
        "A two-bedroom flat in a small block off Aminu Kano Crescent. Now let on a one-year term. Listed here as a recent letting comparable.",
      listingType: "RENT",
      type: "apartment",
      status: "RENTED",
      price: 6_500_000,
      bedrooms: 2,
      bathrooms: 2,
      toilets: 2,
      parking: 1,
      size: 95,
      year: 2013,
      address: "Aminu Kano Crescent",
      area: "Wuse 2",
      city: "Abuja",
      state: "FCT",
      lat: 9.07,
      lng: 7.48,
      agent: "agt_amara",
      agency: "agc_northbridge",
      daysAgo: 70,
      views: 455,
      images: [img("photo-1502672260266-1c1ef2d93688"), img("photo-1522708323590-d24dbb6b0267")],
      amenities: ["parking", "generator", "security", "air-conditioning"],
    },
    {
      id: "prop_pending_villa",
      slug: "katampe-extension-villa-review",
      title: "Katampe Extension Villa",
      description:
        "A newly completed five-bedroom villa awaiting platform verification. Stone cladding, a double-volume entrance, and a pool. Submitted by Northbridge for review.",
      listingType: "SALE",
      type: "villa",
      status: "PENDING_REVIEW",
      price: 410_000_000,
      bedrooms: 5,
      bathrooms: 6,
      toilets: 7,
      parking: 5,
      size: 740,
      land: 1100,
      year: 2026,
      address: "Katampe Extension",
      area: "Katampe",
      city: "Abuja",
      state: "FCT",
      lat: 9.1,
      lng: 7.46,
      agent: "agt_amara",
      agency: "agc_northbridge",
      daysAgo: 1,
      views: 12,
      images: [
        img("photo-1613977257363-707ba9348227"),
        img("photo-1600596542815-ffad4c1539a9"),
        img("photo-1512917774080-9991f1c4c750"),
      ],
      amenities: [
        "swimming-pool",
        "parking",
        "generator",
        "security",
        "air-conditioning",
        "garden",
        "gym",
        "cctv",
        "electricity",
        "water",
      ],
    },
    {
      id: "prop_ibadan_shop",
      slug: "bodija-retail-unit",
      title: "Bodija Retail Unit",
      description:
        "A 68 sqm lock-up shop on a busy Bodija frontage. Roller shutter, small store at the rear, and a shared generator. Suitable for fashion, pharmacy, or a services desk. Lease of three years preferred.",
      listingType: "LEASE",
      type: "shop",
      status: "AVAILABLE",
      price: 4_800_000,
      size: 68,
      year: 2009,
      address: "Bodija Market Road",
      area: "Bodija",
      city: "Ibadan",
      state: "Oyo",
      lat: 7.431,
      lng: 3.913,
      agent: "agt_yusuf",
      agency: "agc_capitalcrest",
      daysAgo: 25,
      views: 77,
      images: [img("photo-1441986300917-64674bd600d8")],
      amenities: ["generator", "security"],
    },
    {
      id: "prop_calabar_apt",
      slug: "calabar-hilltop-apartment",
      title: "Calabar Hilltop Apartment",
      description:
        "A three-bedroom apartment with a long view toward the river. Recently refurbished, with new air-conditioning and a backup inverter. A calm, well-kept building of only eight flats.",
      listingType: "RENT",
      type: "apartment",
      status: "AVAILABLE",
      price: 5_200_000,
      bedrooms: 3,
      bathrooms: 3,
      toilets: 3,
      parking: 2,
      size: 140,
      year: 2018,
      address: "Marian Road",
      area: "Marian",
      city: "Calabar",
      state: "Cross River",
      lat: 4.9757,
      lng: 8.3417,
      agent: "agt_fatima",
      agency: "agc_capitalcrest",
      verified: true,
      daysAgo: 8,
      views: 121,
      images: [
        img("photo-1560448204-e02f11c3d0e2"),
        img("photo-1502672260266-1c1ef2d93688"),
        img("photo-1484154218962-a197022b5858"),
      ],
      amenities: ["parking", "generator", "security", "air-conditioning", "balcony", "water"],
    },
  ];
  for (const p of properties) {
    const published =
      p.status === "PENDING_REVIEW" || p.status === "DRAFT" ? null : daysAgoIso(p.daysAgo);
    await sql`
      insert into properties (
        id, slug, title, description, listing_type, property_type_id, status, price, currency,
        bedrooms, bathrooms, toilets, parking, size_sqm, land_size_sqm, year_built,
        address, area, city, state, country, lat, lng, agent_id, agency_id,
        is_featured, is_verified, views, published_at, available_from, created_at, updated_at
      ) values (
        ${p.id}, ${p.slug}, ${p.title}, ${p.description}, ${p.listingType}, ${typeId(p.type)}, ${p.status},
        ${p.price}, 'NGN', ${p.bedrooms ?? null}, ${p.bathrooms ?? null}, ${p.toilets ?? null},
        ${p.parking ?? null}, ${p.size ?? null}, ${p.land ?? null}, ${p.year ?? null},
        ${p.address}, ${p.area}, ${p.city}, ${p.state}, 'Nigeria', ${p.lat}, ${p.lng},
        ${p.agent}, ${p.agency}, ${p.featured ?? false}, ${p.verified ?? false}, ${p.views},
        ${published}, ${p.availableFrom ?? null}, ${daysAgoIso(p.daysAgo)}, ${daysAgoIso(p.daysAgo)}
      )`;
    for (let i = 0; i < p.images.length; i += 1) {
      await sql`
        insert into property_images (property_id, url, alt, sort_order, is_primary)
        values (${p.id}, ${p.images[i]}, ${p.title}, ${i}, ${i === 0})`;
    }
    for (const slug of p.amenities) {
      await sql`insert into property_amenities (property_id, amenity_id) values (${p.id}, ${amenityId(slug)})`;
    }
  }
  const reviews = [
    [
      "rev_1",
      "seed_ada",
      "agt_amara",
      null,
      5,
      "Amara was exact, unhurried, and unusually well briefed on title. We completed in six weeks.",
    ],
    [
      "rev_2",
      "seed_kunle",
      "agt_amara",
      null,
      5,
      "The Wuse viewing was organised properly — keys, generator test, and a written snag list.",
    ],
    [
      "rev_3",
      "seed_maya",
      "agt_tunde",
      null,
      5,
      "Tunde understands the Ikoyi market in a way that saved us from a poorly specified penthouse.",
    ],
    [
      "rev_4",
      "seed_ibrahim",
      "agt_tunde",
      null,
      4,
      "Slightly slower on paperwork than hoped, but the outcome was right.",
    ],
    [
      "rev_5",
      "seed_ada",
      "agt_ifeoma",
      null,
      5,
      "Inventories were meticulous. The Lekki apartment was as described.",
    ],
    [
      "rev_6",
      "seed_chioma",
      "agt_fatima",
      null,
      4,
      "Corporate letting handled cleanly. Would use again for staff housing.",
    ],
    [
      "rev_7",
      "seed_kunle",
      null,
      "agc_northbridge",
      5,
      "A serious Abuja practice. No theatre, just good stock and clear advice.",
    ],
    [
      "rev_8",
      "seed_maya",
      null,
      "agc_atelier",
      5,
      "The best island specialists we met. Photography and particulars were accurate.",
    ],
    [
      "rev_9",
      "seed_ibrahim",
      null,
      "agc_capitalcrest",
      4,
      "Reliable on GRA lets. Communication could be a little tighter.",
    ],
  ];
  for (const [id, user, agent, agency, rating, body] of reviews) {
    await sql`
      insert into reviews (id, user_id, agent_id, agency_id, rating, body, created_at)
      values (${id}, ${user}, ${agent}, ${agency}, ${rating}, ${body}, ${daysAgoIso(20)})`;
  }
  await sql`
    insert into inquiries (
      id, user_id, property_id, agent_id, name, email, phone, message, contact_method, status, created_at
    ) values (
      'inq_seed_1', 'seed_ada', 'prop_wuse_duplex', 'agt_amara',
      'Adaeze Nwankwo', 'adaeze@example.com', '+234 803 111 2002',
      'We would like to view the Wuse duplex this weekend if possible. A family of four, cash buyers.',
      'EMAIL', 'OPEN', ${daysAgoIso(2)}
    )`;
  await sql`
    insert into appointments (
      id, user_id, property_id, agent_id, preferred_date, preferred_time, message, status, created_at
    ) values (
      'apt_seed_1', 'seed_kunle', 'prop_ikoyi_penthouse', 'agt_tunde',
      ${new Date(Date.now() + 3 * 86_400_000).toISOString().slice(0, 10)},
      '11:00',
      'Please allow 45 minutes. We are flying in from Abuja that morning.',
      'CONFIRMED', ${daysAgoIso(1)}
    )`;
}
