/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgenciesIndexRouteImport } from './routes/agencies/index'
import { Route as AgenciesSlugRouteImport } from './routes/agencies/$slug'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsSlugRouteImport } from './routes/agents/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardAgentRouteImport } from './routes/dashboard/agent'
import { Route as DashboardClientRouteImport } from './routes/dashboard/client'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as ApiAgenciesIndexRouteImport } from './routes/api/agencies/index'
import { Route as ApiAgentsIndexRouteImport } from './routes/api/agents/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPropertiesIndexRouteImport } from './routes/api/properties/index'
import { Route as ApiPropertiesIdRouteImport } from './routes/api/properties/$id'
import { Route as DashboardListingsIdRouteImport } from './routes/dashboard/listings.$id'
import { Route as DashboardListingsNewRouteImport } from './routes/dashboard/listings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/agencies/$slug',
  path: '/agencies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/dashboard/agent',
  path: '/dashboard/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientRoute = DashboardClientRouteImport.update({
  id: '/dashboard/client',
  path: '/dashboard/client',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgenciesIndexRoute = ApiAgenciesIndexRouteImport.update({
  id: '/api/agencies/',
  path: '/api/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIndexRoute = ApiAgentsIndexRouteImport.update({
  id: '/api/agents/',
  path: '/api/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesIndexRoute = ApiPropertiesIndexRouteImport.update({
  id: '/api/properties/',
  path: '/api/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesIdRoute = ApiPropertiesIdRouteImport.update({
  id: '/api/properties/$id',
  path: '/api/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardListingsIdRoute = DashboardListingsIdRouteImport.update({
  id: '/dashboard/listings/$id',
  path: '/dashboard/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardListingsNewRoute = DashboardListingsNewRouteImport.update({
  id: '/dashboard/listings/new',
  path: '/dashboard/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/client': typeof DashboardClientRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/properties/$id': typeof ApiPropertiesIdRoute
  '/dashboard/listings/$id': typeof DashboardListingsIdRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/api/agencies/': typeof ApiAgenciesIndexRoute
  '/api/agents/': typeof ApiAgentsIndexRoute
  '/api/properties/': typeof ApiPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/client': typeof DashboardClientRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/agencies': typeof AgenciesIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/properties/$id': typeof ApiPropertiesIdRoute
  '/dashboard/listings/$id': typeof DashboardListingsIdRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/api/agencies': typeof ApiAgenciesIndexRoute
  '/api/agents': typeof ApiAgentsIndexRoute
  '/api/properties': typeof ApiPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/client': typeof DashboardClientRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/properties/$id': typeof ApiPropertiesIdRoute
  '/dashboard/listings/$id': typeof DashboardListingsIdRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/api/agencies/': typeof ApiAgenciesIndexRoute
  '/api/agents/': typeof ApiAgentsIndexRoute
  '/api/properties/': typeof ApiPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/login'
    | '/agencies/$slug'
    | '/agents/$slug'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/client'
    | '/properties/$slug'
    | '/agencies/'
    | '/agents/'
    | '/dashboard/'
    | '/properties/'
    | '/api/auth/$'
    | '/api/properties/$id'
    | '/dashboard/listings/$id'
    | '/dashboard/listings/new'
    | '/api/agencies/'
    | '/api/agents/'
    | '/api/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/login'
    | '/agencies/$slug'
    | '/agents/$slug'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/client'
    | '/properties/$slug'
    | '/agencies'
    | '/agents'
    | '/dashboard'
    | '/properties'
    | '/api/auth/$'
    | '/api/properties/$id'
    | '/dashboard/listings/$id'
    | '/dashboard/listings/new'
    | '/api/agencies'
    | '/api/agents'
    | '/api/properties'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/login'
    | '/agencies/$slug'
    | '/agents/$slug'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/client'
    | '/properties/$slug'
    | '/agencies/'
    | '/agents/'
    | '/dashboard/'
    | '/properties/'
    | '/api/auth/$'
    | '/api/properties/$id'
    | '/dashboard/listings/$id'
    | '/dashboard/listings/new'
    | '/api/agencies/'
    | '/api/agents/'
    | '/api/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardClientRoute: typeof DashboardClientRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPropertiesIdRoute: typeof ApiPropertiesIdRoute
  DashboardListingsIdRoute: typeof DashboardListingsIdRoute
  DashboardListingsNewRoute: typeof DashboardListingsNewRoute
  ApiAgenciesIndexRoute: typeof ApiAgenciesIndexRoute
  ApiAgentsIndexRoute: typeof ApiAgentsIndexRoute
  ApiPropertiesIndexRoute: typeof ApiPropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/agencies/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/dashboard/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client': {
      id: '/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof DashboardClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agencies/': {
      id: '/api/agencies/'
      path: '/api/agencies'
      fullPath: '/api/agencies/'
      preLoaderRoute: typeof ApiAgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/': {
      id: '/api/agents/'
      path: '/api/agents'
      fullPath: '/api/agents/'
      preLoaderRoute: typeof ApiAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/': {
      id: '/api/properties/'
      path: '/api/properties'
      fullPath: '/api/properties/'
      preLoaderRoute: typeof ApiPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/$id': {
      id: '/api/properties/$id'
      path: '/api/properties/$id'
      fullPath: '/api/properties/$id'
      preLoaderRoute: typeof ApiPropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/listings/$id': {
      id: '/dashboard/listings/$id'
      path: '/dashboard/listings/$id'
      fullPath: '/dashboard/listings/$id'
      preLoaderRoute: typeof DashboardListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/listings/new': {
      id: '/dashboard/listings/new'
      path: '/dashboard/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof DashboardListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  AgenciesSlugRoute: AgenciesSlugRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardClientRoute: DashboardClientRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPropertiesIdRoute: ApiPropertiesIdRoute,
  DashboardListingsIdRoute: DashboardListingsIdRoute,
  DashboardListingsNewRoute: DashboardListingsNewRoute,
  ApiAgenciesIndexRoute: ApiAgenciesIndexRoute,
  ApiAgentsIndexRoute: ApiAgentsIndexRoute,
  ApiPropertiesIndexRoute: ApiPropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
